import { NextResponse } from 'next/server';
import { logEvent } from '@/lib/sheets';
import { uploadVideoFromUrl, postPinnedComment } from '@/lib/youtube';

export async function POST() { return GET(); }

export async function GET() {
  // Demo: schedule two dry-run uploads
  const now = new Date();
  const vids = [] as any[];
  for (let i = 0; i < 2; i++) {
    const title = `Demo Short #${i + 1}`;
    const description = 'Autogenerated by Agentic Clips\n#shorts #podcast';
    const res = await uploadVideoFromUrl({ url: 'https://example.com/video.mp4', title, description, scheduleAt: now });
    const comment = await postPinnedComment(res.id, '🔥 What would you have said here? Drop it below 👇');
    vids.push({ upload: res, comment });
  }
  await logEvent('schedule', { count: vids.length });
  return NextResponse.json({ ok: true, vids });
}
